# Generated by Django 4.0.5 on 2022-11-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pso', '0002_ringkasan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringkasan',
            name='ringkasan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ringkasan',
            name='teks_asli',
            field=models.TextField(),
        ),
    ]
