# Generated by Django 4.0.5 on 2022-12-01 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pso', '0003_alter_ringkasan_ringkasan_alter_ringkasan_teks_asli'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='teks',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
