# Generated by Django 4.0.5 on 2022-12-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pso', '0004_berita_teks'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
