# Generated by Django 4.0.5 on 2022-12-01 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pso', '0005_berita_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='name',
            new_name='judul',
        ),
    ]
