# Generated by Django 4.0.5 on 2022-12-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pso', '0006_rename_name_berita_judul'),
    ]

    operations = [
        migrations.AddField(
            model_name='ringkasan',
            name='iteration',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ringkasan',
            name='kalimat',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='ringkasan',
            name='particle',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ringkasan',
            name='timelapsed',
            field=models.IntegerField(default=None, verbose_name='Time Lapsed (seconds)'),
        ),
        migrations.AddField(
            model_name='ringkasan',
            name='total_sebelum',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ringkasan',
            name='total_sesudah',
            field=models.IntegerField(default=None),
        ),
    ]
