# Generated by Django 4.0.5 on 2022-12-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pso', '0007_ringkasan_iteration_ringkasan_kalimat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='file',
            field=models.FileField(default=None, max_length=255, upload_to=''),
        ),
    ]
