# Generated by Django 4.0.5 on 2022-12-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pso', '0009_ringkasan_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('teks_asli', models.TextField()),
                ('ringkasan_pso', models.TextField()),
                ('kalimat_pso', models.CharField(default=None, max_length=255)),
                ('iteration_done_pso', models.IntegerField(default=None)),
                ('iteration_pso', models.IntegerField(default=None)),
                ('particle_pso', models.IntegerField(default=None)),
                ('timelapsed_pso', models.IntegerField(default=None, verbose_name='Time Lapsed (seconds)')),
                ('total_sebelum_pso', models.IntegerField(default=None)),
                ('total_sesudah_pso', models.IntegerField(default=None)),
                ('ringkasan_pfnet', models.TextField()),
                ('kalimat_pfnet', models.CharField(default=None, max_length=255)),
                ('iteration_done_pfnet', models.IntegerField(default=None)),
                ('iteration_pfnet', models.IntegerField(default=None)),
                ('particle_pfnet', models.IntegerField(default=None)),
                ('timelapsed_pfnet', models.IntegerField(default=None, verbose_name='Time Lapsed (seconds)')),
                ('total_sebelum_pfnet', models.IntegerField(default=None)),
                ('total_sesudah_pfnet', models.IntegerField(default=None)),
            ],
        ),
    ]
