# Generated by Django 4.0.5 on 2022-12-10 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pso', '0010_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
