# Generated by Django 4.0.5 on 2022-12-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pso', '0011_comparison_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonfile', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('judul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pso.berita')),
            ],
        ),
    ]
