# Generated by Django 4.0.5 on 2022-12-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pso', '0012_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='judul',
            field=models.CharField(max_length=255),
        ),
    ]
