# Generated by Django 4.0.5 on 2022-12-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pso', '0013_alter_testing_judul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='jsonfile',
            field=models.CharField(max_length=255, verbose_name='JSON File'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='judul',
            field=models.CharField(max_length=255, verbose_name='Berita'),
        ),
    ]
