# Generated by Django 4.0.5 on 2022-12-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pso', '0014_alter_testing_created_alter_testing_jsonfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='jsonfile',
        ),
        migrations.AddField(
            model_name='testing',
            name='data_json',
            field=models.JSONField(null=True, verbose_name='JSON'),
        ),
    ]
